{% set name = "gistim" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gistim-{{ version }}.tar.gz
  sha256: b78637917f2ac2f4def2675e0e84bc4c5f68862ee9718053ded979bd12f97323

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - black
    - fiona
    - geopandas
    - matplotlib-base
    - lmfit >=1.0
    - netCDF4
    - numba >=0.50
    - numpy
    - python >=3.7
    - rasterio <=1.2.10
    - rioxarray
    - scipy >=1.5
    - shapely
    - tqdm
    - timml
    - xarray >=0.15

test:
  imports:
    - gistim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/deltares/imod/qgis-tim
  summary: GIS utilities for Tim(ML) Analytic Element modeling
  license: GPL-2.0-or-later
  license_file: LICENSE
  doc_url: https://deltares.gitlab.io/imod/qgis-tim
  dev_url: https://gitlab.com/deltares/imod/qgis-tim

extra:
  recipe-maintainers:
    - Huite
    - visr
